//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footer
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> Copywrite_date { get; set; }
        public string Instagram_link { get; set; }
        public string Facebook_link { get; set; }
        public string Twitter_link { get; set; }
        public string Adress { get; set; }
    }
}
