//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Written_date { get; set; }
        public Nullable<int> View_Count { get; set; }
        public Nullable<int> SinglePost_id { get; set; }
        public Nullable<int> ImgMedium_id { get; set; }
        public Nullable<int> ImgSmall_id { get; set; }
        public Nullable<int> ImgCompetitions_id { get; set; }
        public Nullable<int> ImgHomePage_id { get; set; }
        public string SubTitle { get; set; }
        public Nullable<int> Category1_id { get; set; }
        public Nullable<int> Category2_id { get; set; }
        public Nullable<int> Author_id { get; set; }
        public Nullable<int> Page_home_id { get; set; }
        public Nullable<int> Page_Competitions_id { get; set; }
        public Nullable<int> Page_List_id { get; set; }
        public Nullable<int> Page_SinglePost_id { get; set; }
        public Nullable<int> Page_Isotop_id { get; set; }
        public Nullable<int> Page_Partner_id { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual CompetitionsImg CompetitionsImg { get; set; }
        public virtual HomePageImg HomePageImg { get; set; }
        public virtual Page Page { get; set; }
        public virtual Page Page1 { get; set; }
        public virtual Page Page2 { get; set; }
        public virtual Page Page3 { get; set; }
        public virtual Page Page4 { get; set; }
        public virtual Page Page5 { get; set; }
        public virtual PostCategory PostCategory { get; set; }
        public virtual PostCategory PostCategory1 { get; set; }
        public virtual PostImgMedium PostImgMedium { get; set; }
        public virtual PostImgSmall PostImgSmall { get; set; }
        public virtual SinglePost SinglePost { get; set; }
    }
}
