//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Product_to_Brands = new HashSet<Product_to_Brands>();
            this.Product_to_Categories = new HashSet<Product_to_Categories>();
            this.Product_to_SingleLarge = new HashSet<Product_to_SingleLarge>();
            this.Product_to_SingleMini = new HashSet<Product_to_SingleMini>();
        }
    
        public int Id { get; set; }
        public string Price { get; set; }
        public string Old_price { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public Nullable<int> Count { get; set; }
        public string Icon1 { get; set; }
        public string Icon2 { get; set; }
        public string Icon3 { get; set; }
        public string Icon4 { get; set; }
        public string Icon5 { get; set; }
        public Nullable<int> ImgMedium_id { get; set; }
        public Nullable<int> ImgSmall_id { get; set; }
        public Nullable<int> ImgMini_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_to_Brands> Product_to_Brands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_to_Categories> Product_to_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_to_SingleLarge> Product_to_SingleLarge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_to_SingleMini> Product_to_SingleMini { get; set; }
        public virtual ProductImgMedium ProductImgMedium { get; set; }
        public virtual ProductImgMini ProductImgMini { get; set; }
        public virtual ProductImgSmall ProductImgSmall { get; set; }
    }
}
